kind: pipeline
type: kubernetes
name: build-rest-api

steps:
- name: "git submodule"
  image: alpine/git
  commands:
  - git submodule init && git submodule update

- name: "build"
  image: node:lts-alpine
  commands:
  - yarn && yarn prisma generate && yarn tsc && npm prune --production

- name: docker  
  image: plugins/docker
  settings:
    repo: 
      from_secret: docker_repo
    registry: 
      from_secret: docker_registry
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: danielgormly/drone-plugin-kube:0.2.0
  settings:
    template: k8s/deployment.yaml
    namespace:
      from_secret: k8s_namespace
    ca: 
      from_secret: k8s_ca
    server: 
      from_secret: k8s_server
    token:
      from_secret: k8s_token