kind: pipeline
type: kubernetes
name: build-rest-api

steps:
- name: "git submodule"
  image: alpine/git
  commands:
  - git submodule init && git submodule update

- name: "build"
  image: node:lts-alpine
  commands:
  - yarn && yarn prisma generate && yarn tsc && npm prune --production

- name: docker  
  image: plugins/docker
  settings:
    repo: registry.arrakis.ovh/doncicuto/dir3-rest-api
    registry: registry.arrakis.ovh
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
